apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"backend"},"name":"backend","namespace":"ahmadreza-navid-ns"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"backend"}},"template":{"metadata":{"labels":{"app":"backend"}},"spec":{"containers":[{"image":"quay.io/ahmadrezasy/joboonja-backend","imagePullPolicy":"Always","name":"backend","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{"limits":{"cpu":"400m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"64Mi"}}}],"restartPolicy":"Always","securityContext":{}}}},"status":{}}
  creationTimestamp: null
  generation: 1
  labels:
    app: backend
  name: backend
  namespace: ahmadreza-navid-ns
  selfLink: /apis/extensions/v1beta1/namespaces/ahmadreza-navid-ns/deployments/backend
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: quay.io/ahmadrezasy/joboonja-backend:latest
        imagePullPolicy: Always
        name: backend
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
